print(" ------------------------------------------------") 
print("|                                                |")
print("|    O2GoodbyeWorld                              |")
print("|    Name : Nikhita Arora                        |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
print("Hello World")