print(" ------------------------------------------------") 
print("|                                                |")
print("|    O3GoodbyePerson                             |")
print("|    Name : Nikhita Arora                        |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
print("Hello")
print("What is your name?")
username = input("What is your name ? ")
print("Goodbye " + username)