print(" ------------------------------------------------") 
print("|                                                |")
print("|    O2GoodbyePerson                             |")
print("|    Name : Nikhita Arora                        |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
print("Hello")
print("What is your name?")