print(" ------------------------------------------------") 
print("|                                                |")
print("|    O4GoodTeacher                               |")
print("|    Name : Nikhita Arora                        |")
print("|    Version : 01                                |")
print("|                                                |")
print(" ------------------------------------------------")
print("Teacher's name (try Mr Horan")
